services:

  #grafana:
  #  image: grafana/grafana:latest
  #  ports:
  #    - "3001:3000" #map Grafana container's 3000 port to host's 3001
  #  volumes:
  #    - ./grafana/provisioning:/etc/grafana/provisioning
  #    - grafana-storage:/var/lib/grafana
  #  environment:
  #    - GF_SECURITY_ADMIN_USER=admin
  #     - GF_SECURITY_ADMIN_PASSWORD=adminpassword
  #  depends_on:
  #    - postgres
  #  networks:
  #    - app-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
      TZ: Asia/Kolkata  # Change DBeaver timezone settings
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data1     #if there are initialization errors after multiple runs --> docker rm -f $(docker ps -a -q),  docker volume rm customapp_postgres-data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  python:     # Frontend container - FastAPI server only
    build:
      context: ./Custom-App
      dockerfile: Dockerfile.main
    ports:
      - "8000:8000"  # FastAPI
    restart: unless-stopped
    volumes:
      - ./Custom-App/app:/app
      - ./start.sh:/start.sh   # Mount start.sh
    depends_on:
      - postgres
    networks:
      - app-network
    command: ["bash", "/start.sh"]

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - app-network
    volumes:
      - redis-data:/data

  python-tasks:     # Background tasks container - cron jobs + on-demand API
    build:
      context: ./Custom-App
      dockerfile: app/task-services/Dockerfile.tasks
    ports:
      - "8001:8001"  # FastAPI for on-demand task triggers
    restart: unless-stopped
    volumes:
      - ./Custom-App/app:/app
    depends_on:
      - postgres
    networks:
      - app-network
    # Command is set in Dockerfile.tasks, no need to override here


volumes:
  grafana-storage:
  postgres-data:
  redis-data:

networks:
  app-network:
    driver: bridge
